### PR TITLE
Fallout 4 updates:

### PR DESCRIPTION
**Pull request by lojack5**
I adjusted the labels on wrye-bash/wrye-bash since Fallout 4 support will be a thing shortly.

This requires an update to the scripts used to recognize that label and the renamed label for Fallout 3.

@Utumno : I wanted to do this directly, but I'd also like to setup the text files for first post, second post, and nexus pages.  I noticed that the 306 release stuff isn't in master yet though, did you want to merge that first?  If so, then I'll edit this branch to include starter posts, etc for Fallout 4.

### CODE REVIEW

**Comment by Utumno** [comment]
Yes I haven't yet done that - please make your changes on top of utumno-rel-306 branch and let me merge those - just rebawe this in top of mine

Btw - the automaton is broken - could you fix it (I think I can't, I need its login ? not sure)

**Comment by lojack5** [comment]
Yeah, I saw that I'll look into it.  And will do on the rebase stuff.

**Comment by lojack5** [comment]
Ok, annoying github feature: I cannot change which branch I want to merge this into.  Oh well, I realized that since we do not actually have an official thread on the fallout 4 page yet, I won't be updating anything else actually.  This is all that's needed so the release procedure doesn't fail on the new game tags.

I will open an Issue to remind us to add that information in though once we go and make a first official release on the Fallout 4 forums.

**Comment by Utumno** [comment]
All done here :)

Please leave an empty line after the commit subject - plays well with git in general (for instance rebase commit message)

**Comment by lojack5** [comment]
Wasn't aware of that, ok

**Pull request closed without merging**
